<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>6b6ded70-2a31-4071-ac52-c062d4faf84b</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.24" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Shared\MyRecioeBook.Communication\MyRecipeBook.Communication.csproj" />
    <ProjectReference Include="..\..\Shared\MyRecipeBook.Exceptions\MyRecipeBook.Exceptions.csproj" />
    <ProjectReference Include="..\MyRecipeBook.Application\MyRecipeBook.Application\MyRecipeBook.Application.csproj" />
    <ProjectReference Include="..\MyRecipeBook.infrastructure\MyRecipeBook.Infrastructure.csproj" />
  </ItemGroup>

</Project>
